// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: grpc/ChitChat.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_grpc_ChitChat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_ChitChat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_grpc_ChitChat_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *Message) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_grpc_ChitChat_proto protoreflect.FileDescriptor

const file_grpc_ChitChat_proto_rawDesc = "" +
	"\n" +
	"\x13grpc/ChitChat.proto\x12\bChitChat\"9\n" +
	"\aMessage\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp2E\n" +
	"\x0eMessageService\x123\n" +
	"\aConnect\x12\x11.ChitChat.Message\x1a\x11.ChitChat.Message(\x010\x01B\x0fZ\rChitChat/grpcb\x06proto3"

var (
	file_grpc_ChitChat_proto_rawDescOnce sync.Once
	file_grpc_ChitChat_proto_rawDescData []byte
)

func file_grpc_ChitChat_proto_rawDescGZIP() []byte {
	file_grpc_ChitChat_proto_rawDescOnce.Do(func() {
		file_grpc_ChitChat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_ChitChat_proto_rawDesc), len(file_grpc_ChitChat_proto_rawDesc)))
	})
	return file_grpc_ChitChat_proto_rawDescData
}

var file_grpc_ChitChat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_grpc_ChitChat_proto_goTypes = []any{
	(*Message)(nil), // 0: ChitChat.Message
}
var file_grpc_ChitChat_proto_depIdxs = []int32{
	0, // 0: ChitChat.MessageService.Connect:input_type -> ChitChat.Message
	0, // 1: ChitChat.MessageService.Connect:output_type -> ChitChat.Message
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_grpc_ChitChat_proto_init() }
func file_grpc_ChitChat_proto_init() {
	if File_grpc_ChitChat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_ChitChat_proto_rawDesc), len(file_grpc_ChitChat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_ChitChat_proto_goTypes,
		DependencyIndexes: file_grpc_ChitChat_proto_depIdxs,
		MessageInfos:      file_grpc_ChitChat_proto_msgTypes,
	}.Build()
	File_grpc_ChitChat_proto = out.File
	file_grpc_ChitChat_proto_goTypes = nil
	file_grpc_ChitChat_proto_depIdxs = nil
}
